### ISSUE TITLE
哔哩哔哩签到报错，前几天还正常。

### ISSUE THREAD

**Issue by yulinsoft** [he1pu/signin#6]
🔔哔哩哔哩签到, 开始!

=========共1个哔哩哔哩账号Cookie=========

=========脚本执行- 北京时间(UTC+8)：2021/11/22 上午9:10:32=========

*********开始【哔哩哔哩账号1】********

获取用户信息成功
漫画签到: 成功
直播签到: 成功，3000点用户经验,2根辣条，特别信息：再签到8天可以获得50根辣条，本月已签到12天
获取漫画大会员福利: 不是vip用户哦～
给关注的up投币

❗️哔哩哔哩签到, 错误!
TypeError: Cannot read properties of undefined (reading 'aid')
    at run (/ql/scripts/he1pu_signin/_bili.js:196:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /ql/scripts/he1pu_signin/_bili.js:47:7
钉钉发送通知消息成功🎉。

🔔哔哩哔哩签到, 结束! 🕛 13.425 秒

**Comment by he1pu** [comment]
网络问题吧，重新运行试试

**Comment by haohaoget** [comment]
> 🔔哔哩哔哩签到, 开始!
> 
> =========共1个哔哩哔哩账号Cookie=========
> 
> =========脚本执行- 北京时间(UTC+8)：2021/11/22 上午9:10:32=========
> 
> *********开始【哔哩哔哩账号1】********
> 
> 获取用户信息成功 漫画签到: 成功 直播签到: 成功，3000点用户经验,2根辣条，特别信息：再签到8天可以获得50根辣条，本月已签到12天 获取漫画大会员福利: 不是vip用户哦～ 给关注的up投币
> 
> ❗️哔哩哔哩签到, 错误! TypeError: Cannot read properties of undefined (reading 'aid') at run (/ql/scripts/he1pu_signin/_bili.js:196:25) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async /ql/scripts/he1pu_signin/_bili.js:47:7 钉钉发送通知消息成功🎉。
> 
> 🔔哔哩哔哩签到, 结束! 🕛 13.425 秒

同样的我也是这个，好像是哔哩哔哩那边拒绝了吧

**Comment by gigi2u** [comment]
❗️哔哩哔哩签到, 错误!
TypeError: Cannot read properties of undefined (reading 'list')
    at space_arc_search (/ql/scripts/he1pu_signin/_bili.js:289:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/ql/scripts/he1pu_signin/_bili.js:161:22)
    at async /ql/scripts/he1pu_signin/_bili.js:47:7
Telegram发送通知消息成功🎉。
